# Numpy - Creating and saving NumPy `ndarrays`

## 1. Introduction
At the core of Numpy is the **ndarray**, where *nd* stands for *n-dimensional*. An `ndarray`is a multidimentional array of elements all of the same type. In other words, an ndarray is a grid that can take on many shapes and can hold eighter numbers or srings. In many Machine Learning problems you will often find yourself using ndarrays in many different ways. For instance, you might use an ndarray to hold the pixel values of an image that will be fed into a Neural Netwrok for image classificaion.

But before we can dive in and strart using NumPy to create ndarrays we need o import it into Python. We can import packages into Python using the `import`command and it has become a convertion to import NumPy as `np`. Therefore, you can import Numpy as it is shown in the cell below.

In [1]:
import numpy as np 



## 2. Creating NumPy ndarrays

There are several ways to create ndarrays in NumPy. In the following lessons we will se two ways o creat ndarrays:

1. Using regular Python lists.
2. Using built-in NumPy functions.

In this section, is explained the creation of ndarrays by providing Python lists to the NumPy `np.array()` function. This can create some confusion for beginners, but it is important to remember that `np.array()` **is NOT A CLASS**, it is just a function that returns an ndarray. We should noe that for the purposes of clarity, the examples throughout these lessons will use small and simple ndarrays. Let's start by creating 1-Dimensional (1D) ndarrays.

In [ ]:
x = np.array([1,2,3,4,5])

In [2]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## 3. Rank of an Array(numpy.ndarray.ndim)

Syntax:
```
ndarry.ndim
```

It returns the number of arrays dimensions, but not the dimensions (number of elements stored in the array), but the meaning has the mathematical approach. We refer to 1D arrays as *rank 1* arrays. In general N-Dimensional arrays have rank *N*. Therefore, we refer to a 2D array as rank 2 array. 

In [24]:
## 1-D array
x = np.array([1,2,3])
x.ndim

## 2-D array
y = np.array([[1,2,3,],[4,5,6],[7,8,9],[10,11,12]])
y.ndim


2

Here the `zeros()` is an inbuilt function that it will be explained in detail in the next section. In `y = np.zeros((2,3,4))` represents the shape of the ndarray


In [25]:
y = np.zeros((2,3,4))
print(y)
y.ndim

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


3

## 4. numpy.ndarray.shape

Syntax:
```
ndarray.shape
```
It returns a tuple representng the array dimensions.

Another important property of arrays is their shape. The shape of an array is the size along each of tis dimensions. For example, the sape of a rank 2 array sill correspond to the number of *rows* and *columns* of the array. As you will see, NumPy ndarrays have *attributes* that allows us to get information about them in a very intuitive way. For example, the sape of an ndarray can be obtained using `.shape` attribute. The shape attribute return a tuple of N positive integers that specify the sizes of each dimension. 


## 5. numpy.dtype
The **type** tell us the data-type of the elements. Remember, a NumPy array is homogeneous, meaning all elements will have the same data-type. In the example below a 1-rank array is declarad and its attributes are shown. 

In [26]:
x = np.array([1,2,3,4,5])

print('x = ', x)
print('x has dimensions: ', x.shape)
print('x is an object of type: ', type(x))
print('The elements in x are of type: ', x.dtype)

x =  [1 2 3 4 5]
x has dimensions:  (5,)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  int32


It cam be seen that the shape attribute returns the tuple `(5,)` telling us that `x` is of rank 1 (i.e `x` only has 1 dimension) and it has 5 elements. The `type()` function tells us that `x` is indeed a NumPy ndarray. Finally, the `.dtype` attribute tells us that the elements of `x` are instored in memory as *signed 32-bit integers*. Another great advantage of NumPy is that i can handle more data-types than Python lists.

AS mentioned earlier, ndarrays can also hold strings,

In [3]:
x.dtype

dtype('int32')

In [5]:
x.shape

(5,)

In [10]:
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
y.shape

(4, 3)

In [12]:
y.size

12

In [13]:
x = np.array(['Hello','World'])
print(x)

['Hello' 'World']


In [14]:
print('shape: ', x.shape)
print('type: ', type(x))
print('dtyp: ', x.dtype)

shape:  (2,)
type:  <class 'numpy.ndarray'>
dtyp:  <U5


In [15]:
x = np.array([1,2,'World'])
print(x)
print('shape: ', x.shape)
print('type: ', type(x))
print('dtyp: ', x.dtype)

#NOTE NP ARRAYS MUST CONTAIN ELEMENTS OF THE SAME TYPE

['1' '2' 'World']
shape:  (3,)
type:  <class 'numpy.ndarray'>
dtyp:  <U11


In [17]:
x = np.array([1, 2.5, 4])
print(x, x.dtype)
#Although there are integers in the array they are going to be treated as floats, this is upcasting

[1.  2.5 4. ] float64


In [18]:
x = np.array([1.5, 2.2, 3.7])
print(x)
print('dtype: ', x.dtype)

[1.5 2.2 3.7]
dtype:  float64


In [19]:
x = np.array([1,2,3,4,5])
np.save('my_array',x)

In [20]:
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]
