# Using Built-In functions to create ndarrays

## Introduction

In [1]:
import numpy as np

my_list = [1,2,3,4,5]
np.array = (my_list) #convert a list to np array

It is highly recommended to use the built-in function from numpy instead of creating our own functions, this is because the built-in functions might be optmized.

## Creating arrays with zeros and ones. 
The next built-in functions receive as angurment a tuple to indicate the size and shape of the array, the `zeros` creates a nd-array filled with zeros and `ones` creates a nd-array filled with ones, just as in matlab.

As a optional argument a the dtype can be added in order to specify the element's type within the array, observe the next cells.


In [4]:
x = np.zeros((3,4), dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [6]:
y = np.zeros((8,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
p = np.ones((4,5), dtype = int)
q = np.ones((3,3))
print(p)
print(q)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Creating a nd array filled with a single number

With this command, nd-arrays can be created with all the inputs with the same number

In [9]:
x = np.full((4,3), 6, dtype=float)
print(x)

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


## Identity Matrix.

This create the identity matrix, which is a `nxn` matrix filled with zeros and the main diagonal is filled with 1


In [11]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Diagonal Matrix
With the command `np.diag` a diagonal matrix can be done, the arguments that `np.diag` accepts are the main diagonal inputs

In [12]:
x = np.diag([10, 20, 30, 40, 50])
print(x)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [14]:
x = np.arange(10)
print(x)


[0 1 2 3 4 5 6 7 8 9]


In [15]:
x = np.arange(4,10)
print(x)

[4 5 6 7 8 9]


In [16]:
x = np.arange(1,14,3)
print(x)

[ 1  4  7 10 13]


In [18]:
x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [22]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [23]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [25]:
x = np.reshape(x,(4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [27]:
x = np.reshape(x,(10,2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [28]:
y = np.arange(20).reshape((10,2))
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [29]:
q = np.linspace(0,50,10, endpoint=False).reshape(5,2)
print(q)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [30]:
x = np.random.random((3,3))
print(x)

[[0.27408457 0.88561483 0.42346439]
 [0.58485627 0.39118335 0.06573004]
 [0.21947597 0.41492944 0.42222717]]


In [38]:
np.random.randint(2, size=10)

TypeError: 'list' object is not callable

In [40]:
x = np.random.normal(0, 0.1, size=(1000,1000))
print(x)

[[ 0.04088117  0.28223929 -0.16596703 ...  0.15361889  0.02404246
   0.04782692]
 [ 0.01092876 -0.02259543 -0.03736056 ... -0.00839051 -0.03598573
   0.12729761]
 [-0.08340963  0.05473223 -0.11765299 ... -0.09030585 -0.26690433
  -0.1392868 ]
 ...
 [-0.16929537 -0.06182911  0.31948109 ... -0.10067579 -0.18283417
  -0.11338725]
 [-0.17647252 -0.01714555  0.15863916 ...  0.09807636 -0.04197595
   0.06415679]
 [-0.14841723  0.04411871  0.24638595 ... -0.0617172  -0.05708146
   0.06371008]]


In [41]:
X = np.random.randint(4,15,size=(3,2))


TypeError: 'list' object is not callable