# Accesing, Deleting and Inserting Elements Into ndarrays

In previous sessions, the creation of ndarrays has been addressed, in this document, we will now see how NumPy allows us to effectively manipulate the data within the ndarrays. NumPy nd arrays are mutable, meaning that the elements in ndarrays can be changed after the ndarray has been created. Numpy ndarrys can also be sliced, which means that ndarrys can be split in many different ways. This allows us, for example, to retrieve any subset of the ndarry hat we want. Often in Machine Learning you will use slicing to separate data, as for example when dividing data set into training, cross validation and tesing sets. 

We will start by looking at how the elements of an ndarray can be accessed or modified by indexing. Elements can be accessed using indices inside square brackets `[]`. NumPy allows to use both posittive and negative indices to access elements in the ndarray. Positive indices are used to access elements from the beginning of the array, while negative indicees are used to access elements from the end of the array. 

In [6]:
import numpy as np

# Creating a rank 1 ndarray that contains integer from 1 to 5
x = np.arange(1,6)

print()
print('x= ', x)
print()

# Let's access some elements with positive indices
print('This is First Element in x: ', x[0])
print('This is Second Element in x : ', x[1])
print('This is Fifth (Last) Element in x: ', x[4])
print()

# Let's access the same elements with negative indices
print('This is First Element in x: ', x[-5])
print('This is Second Element in x: ', x[-4])
print('This is Fifth (Last) Element in x: ', x[-1])


x=  [1 2 3 4 5]

This is First Element in x:  1
This is Second Element in x :  2
This is Fifth (Last) Element in x:  5

This is First Element in x:  1
This is Second Element in x:  2
This is Fifth (Last) Element in x:  5


Notice that to access the frist element in the ndarray we have to use the index 0 not 1. Also notice, that the same element can be accessed using both positive and negative indices. As mentioned earlier, positive indices are sued to access elements from the beginning of the array, while negative indeces are used to access elemenets from the end of the array. 

## Modify an element of 1-D and 2-D array

Now let's see how we can change the elements in rank 1 ndarrays. We do this by accessing the element we want to change and then using the `=` sign to assign the new value

In [9]:
x = np.arange(1,6)

#We print the original x
print()
print('Original: \n x= ', x)
print()

#we change the fourth element in x from 4 to 20
x[3] = 20

#we print x again
print('Modified: \n x=', x)


Original: 
 x=  [1 2 3 4 5]

Modified: 
 x= [ 1  2  3 20  5]


Similarly, we can also access and modify specific elements of rank 2 ndarrays. To access elements in rank 2 ndarrays we need to provide 2 indices in the form `[row, column]`.

In [11]:
#We create a 3x3 rank 2 ndarray that contains integers from 1 to 9
x = np.arange(1,10).reshape((3,3)) #x=np.array([[1 2 3],[4 5 6],[7 8 9]])

#We print x 
print()
print('x = \n', x)
print()

#Let's access some elements in x
print(f'This is (0,0) Element in X: {x[0,0]}')
print(f'This is (0,1) Element in X: {x[0,1]}')
print(f'This is (2,2) Element in X: {x[2,2]}')


x = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


Remember that the index `[0,0]` refers to the element in the first row, first column.

Elements in rank 2 ndarrays can be modified in the same way as with rank 1 ndarrays.


In [13]:
#We cerate a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

#we print the original x
print()
print('Original:\n X = \n', x)
print()

#we change the (0,0) element in x from 1 to 20
x[0,0] = 20

print()
print('Modified:\n X = \n', x)
print()


Original:
 X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Modified:
 X = 
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]



## Delete elements

Now let's take a look at how we can add and delete elements from ndarrays. We can delete elements using `np.delete(ndarray, elements, axis)` function. This function `deletes` the given list of `elements` from the given `ndarray` along the specified `axis`. For rank 1 ndarrays the `axis` keyword is not required. For rank 2 ndarrays, `axis=0` is used to select *rows*, and `axis=1` is used to select *columns*. Let's see some examples.

In [16]:
#We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

#We create a rank2 ndarray
y = np.array([[1,2,3],[4,5,6],[7,8,9]])

#we print x
print()
print('Original x = ', x)

#we delete the first and last element of x
x=np.delete(x,[0,4])

#we print x with the first and last element deleted
print()
print('Modified x = ', x)

#we print y
print()
print('Original Y = \n', y)

#we delete the frist row of y
w = np.delete(y, 0, axis = 0)

# we delete the frist and the last column of y
v = np.delete(y, [0,2], axis = 1)

# we print w
print()
print("w = \n", w)

# we print v
print()
print("v = \n", v)




Original x =  [1 2 3 4 5]

Modified x =  [2 3 4]

Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

w = 
 [[4 5 6]
 [7 8 9]]

v = 
 [[2]
 [5]
 [8]]


## Numpy.append

Syntax:
```
numpy.append(array, values, axis=None)
```
It appends values to the end of an array.

Now. Let's see how we can append values to ndarrays. We can append values to ndarrays using the ` np.append(ndarray,elements,axis)` function. This function appends the given list of `elements` to `ndarray` along the specified axis. Let's see some examples.


In [19]:
# We create a rank 1 ndarray
x = np.arange(1,6)

# We create a rank 2 ndarray
y = np.arange(1,7).reshape((2,3))

# we print x
print()
print('Original x = ',x)

# we append the integer 6 to x
x = np.append(x,6)

# we print x
print()
print('Modified x = ',x)

# we append the integer 7 and 8 to x
x = np.append(x,[7,8])

# we print x
print()
print('Modified x = ',x)

# we print y
print()
print('Original y = \n', y)

# we append a new row containing 7,8,9 to y
v = np.append(y,[[7,8,9]], axis=0)

# we append a new column containing 9 and 10 to y
q = np.append(y,[[9],[10]], axis =1)

# we print v
print()
print('v = \n',v)

# we print q
print()
print('q = \n',q)


Original x =  [1 2 3 4 5]

Modified x =  [1 2 3 4 5 6]

Modified x =  [1 2 3 4 5 6 7 8]

Original y = 
 [[1 2 3]
 [4 5 6]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

q = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]


Notice that when appending rows or columns to rank 2 ndarrays the rows or columns must have the correct shape, so as to match the shape of the rank 2 ndarray.

## Insert values to ndarray

Now let's see how we can insert values to ndarrays. We can insert values to ndarrays using the `np.insert(ndarray, index, elements, axis)` function. This function inserts the given list of `elements` to `ndarray` right before the given `index` along the specified `axis`. 


In [24]:
# we create a rank 1 ndarray
x = np.array([1, 2, 5, 6, 7])

# we create a rank 2 ndarray
y = np.array([[1,2,3],[7,8,9]])

# we print x
print()
print('Original x = ' , x)

# we insert the integer 3 and 4 between 2 and 5 in x
x = np.insert(x,2,[3,4])

# we print x
print()
print('Modified x = ' , x)

# we print y 
print()
print('Original y = \n ', y)

# we insert a row between the first and last row of y
w = np.insert(y,1,[4,5,6], axis = 0)

# we insert a column of 5s between the first and the second column of y
v = np.insert(y,1,5,axis = 1)

# we print w
print()
print('w = \n', w)

# we print v
print()
print('v = \n', v)




Original x =  [1 2 5 6 7]

Modified x =  [1 2 3 4 5 6 7]

Original y = 
  [[1 2 3]
 [7 8 9]]

w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v = 
 [[1 5 2 3]
 [7 5 8 9]]


## numpy.hstack and numpy.vstack

Syntax:
```
numpy.hstack(sequence_of_ndarray)
```
It returns a stacked array formed by stacking the given arrays in sequence horizontally (column-wise). 

```
numpy.vstack(sequence_of_ndarray)
```
It returns a stacked array formed by stacking the given arrays, will be at least 2-D, in sequence vertically (row-wise). 

Numpy also allows us to stack ndarrays on top of each other, or to stack them side by side. The stacking is done using either the `np.vstack()` function for vertical stacking, or the `np.hstack()` function for horizontal stacking. It is imporant to note that in order to stack ndarrays, the shsape of the ndarrays must match.



In [26]:
# we create a rank 1 ndarray
x = np.array([1,2])

# we create a rank 2 ndarray
y = np.array([[3,4],[5,6]])

# we print x 
print()
print('x = ', x)

# we print y
print()
print('y = \n', y )

# we stack x on top of y
z = np.vstack((x,y))

# we stack x on the right of y. We need to reshape x in order to stack it on the right of y
w = np.hstack((y,x.reshape(2,1)))

# we print z 
print()
print('z = \n', z)

# we print w
print()
print('w = \n', w)


x =  [1 2]

y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]
