# Slicing arrays

It has been meninonted, that we can access to individual elements one at a time, NumPy provides a way to access subsets of ndarrays. This is known as *slicing*. Slicing is performed by comibining indices with the colo `:` symbol inside the square brackets. In general you ill come across three types of slicing

1. `ndarray[start:end]`
2. `ndarray[start:]`
3. `ndarray[:end]`

The first method is used to select elements between the `start` and `end` indices.  The secondone is used to select all elements from the `start` index till the *last* index. The third method is used to select all elements from the *frist* index till the `end` index. We should note that in methods one and three, the end index is excluded. We should also note that since ndarrays canb e multidmensional, when doing slicing you ususally have to specify a slice for each dimension of the array. 

We will see some examples of how to use the above methods to select different subsets of rank 2 ndarray

#### Example 1. Slicing a 2-D ndarray

In [3]:
import numpy as np

# we create a 4 x 5 ndarray that contains integers from 0 to 19
x = np.arange(20).reshape(4,5)

# we print x
print()
print('X = \n', x)
print()

# we select all the elements that are in the 2nd through 4th rows and in the 3re to 5th columns
# (The 1st being index 0)
z = x[1:4,2:5]

# we print z 
print('z = \n', z)


# we can select the same elements as above using method 2
w = x[1:,2:5]

# we print w
print()
print('w = \n', w)

# we select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
y = x[:3,2:5]

# we print y
print()
print(f"Y = \n {y}")

# we select all the elements in the 3rd row
v = x[2,:]

# we print v
print()
print(f"v = \n {v}")

# we select all the elements in the 3rd column
q = x[:,2]

# we print q
print()
print(f"q = \n {q}")

# we select all the elements in the 3rd column but return a rank 2 array
R = x[:,2:3]

# we print r
print()
print(f"r = \n {R}")




X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

w = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

v = 
 [10 11 12 13 14]

q = 
 [ 2  7 12 17]

r = 
 [[ 2]
 [ 7]
 [12]
 [17]]


Notice that when we selected all the elements in the 3rd column, variable `q` above, the slice returned a rank 1 ndarray instead of a rank 2 ndarray. However, slicing `x` in a slightly different way, variable `R` above, we can actually get a rank 2 ndarray instead. 

It is important to note that when we perform slices on ndarrays and save them into new variables, as we did above, the data is not copied into the new variable. This is one feature that often causes confusion for beginners. Therefore, we will look at this in bit more detail.

In the above examples, when we make assignments, such as: 
```
z = x[1:4,2:5]
```
the slice of the original array `x` is not copied in the variable `z`. Rather, `x` and `z` are now just two different names for the same ndarray. We say that slicing only creates a *view* of the original array. this means that if you make changes in `z` you will be in effect changing the elements in `x` as well. Let's see this with an example:

#### Example 2. Slicing and editing elements in a 2-D ndarray

In [4]:
# we create a 4 x 5 ndarray that contains integers from 0 to 19
x = np.arange(20).reshape(4,5)

# we print x
print()
print(f'x = \n {x}')

# we select all the elements that are inthe 2nd through 4th rows and in the 3rd to 4th columns
z = x[1:4,2:5]

# we print z
print()
print(f'z = \n {z}')

# we change the last element in z to 555
z[2,2]=555

# we print x
print()
print(f'x = \n {x}')



x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

x = 
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]


we can clearly see in the above example that if we make changes to `z`, `x` changes as well.

## numpy.ndarray.copy

Syntax:
```
ndarray.copy(order='C')
```
It return a copy of the array.

However, if we want to create a new ndarray that contains a copy of the values in the slice we need to use the `np.copy()` function. The `np.copy(ndarray)` function creates a copy of the given `ndarray`. This function can also be sued as a method, in the same way as we did before with the reshape function. Let's do the same example we did before but now with copies of the arrays. We'll use `copy` both as a function and as a method. 

#### Example 3. Demonstrate the `copy()` function

In [5]:
# we create a 4 x 5 ndarray that contains integers from 0 to 19
x = np.arange(20).reshape(4,5)

# print x
print()
print(f"x: \n {x} ")
print()

# create a copy of the slice using the np.copy() function
z = np.copy(x[1:4,2:5])

# create a copy of the slice using copy as a method
w = x[1:4,2:5].copy()

# change the las elementin z to 555
z[2,2] = 555

# change the last element in w to 444
w[2,2]=444

# print x
print()
print(f"x: \n {x} ")
print()

# print z
print()
print(f"z: \n {z} ")
print()

# print w
print()
print(f"w: \n {w} ")
print()



x: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 


x: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 


z: 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]] 


w: 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]] 



We can clearly see that by using the `copy` command, we are creating new ndarrays that are completely independent of each other. 

It is often useful to use one ndarray to make slices, select, or change elements in another ndarray. Let's see some examples:

#### Example 4a. use an array as indices to either make slices, select, or change elements

In [6]:
# we create a 4x5 ndarray that contains integers from 0 to 19
x = np.arange(20).reshape(4,5)

# create a rank 1 ndarray that will serve as indices to select elements from x
indices = np.array([1,3])

# print x
print()
print(f"x: \n {x} ")
print()

# print indices
print('indices = ', indices)
print()

# use the indices ndarray to select the 2nd and 4th row of x
y = x[indices,:]

# use the indices ndarray to select the 2nd and 4th column of x
z = x[:,indices]

# print y
print()
print(f"y: \n {y} ")

# print x
print()
print(f"z: \n {z} ")


x: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

indices =  [1 3]


y: 
 [[ 5  6  7  8  9]
 [15 16 17 18 19]] 

z: 
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]] 


#### Example 4b Use an array as indices to extract specific rows from a rank 2 ndarray

In [9]:
import numpy as np 

x = np.random.randint(1,20,size=(50,5))

print(f"Shape of x is: {x.shape}")
print(x)

Shape of x is: (50, 5)
[[17  2  5  1 15]
 [12 13  8 17 16]
 [17  2 14 11 15]
 [19  5  5 12 18]
 [19  9  6 16  5]
 [ 3 15  8 13 10]
 [ 9 13 16 18 17]
 [11  4  5 13 19]
 [10  8 12  8 14]
 [ 2 15  4  5  9]
 [14  8  6  1 12]
 [ 6 11 18  4  2]
 [ 5  2  5 13 10]
 [ 2  3  9  1 12]
 [ 8 14  7  3  7]
 [ 3  8  3  5  7]
 [ 3  4  7 13  8]
 [19  4 18  6  6]
 [ 3  7  5  7  4]
 [ 5 11  3 11 11]
 [19 14  9 17  7]
 [ 6  8  3  5 18]
 [ 3  4  9 13 11]
 [ 6  9  7 14  2]
 [13  6 17  8 10]
 [16 17  1 18 19]
 [ 5  5  8  1 17]
 [14  8 19 10 18]
 [ 7  5 19  3  1]
 [ 3  1  1  1  8]
 [18 11 17 17 15]
 [15 14 16 14 17]
 [11 16  5  6  5]
 [17 16  6  4 11]
 [19  6 11 17  2]
 [ 9 13 11 13 10]
 [13  6 14  1  3]
 [ 3 14 11 10  9]
 [ 3  5 18 18 19]
 [11 12 18 14  9]
 [11 19  8  5  5]
 [12 13 17 18 13]
 [10 18  5 11 14]
 [14  8 11 16 13]
 [15 13  2 12  8]
 [ 1  9 10  6 12]
 [ 4  4 12  8  2]
 [ 4 18 17  2  6]
 [ 9  5  3 11 17]
 [10  3  6 17 17]]


In [10]:
# Create a rank 1 ndarray that contains a randomly 10 values between 0 to len(x) (50 )
# The row_indices would represent the indices of rows of x
row_indices = np.random.randint(0,50,size=10)
print(f"Random 10 indices are: ", row_indices)

Random 10 indices are:  [13  1 32 22 44  9 31  4 33 25]


In [11]:
# TODO 1 - Print those rows of x whose indices are represented by entire row_indices ndarray
# Hint - use the row_indices ndarray to select specified rows of x
x_subset = x[row_indices,:]
print(x_subset)

# TODO 2- print those rows of x whose indeces are present in row_indices[4:8]
x_subset = x[row_indices[4:8],:]
print(x_subset)

[[ 2  3  9  1 12]
 [12 13  8 17 16]
 [11 16  5  6  5]
 [ 3  4  9 13 11]
 [15 13  2 12  8]
 [ 2 15  4  5  9]
 [15 14 16 14 17]
 [19  9  6 16  5]
 [17 16  6  4 11]
 [16 17  1 18 19]]
[[15 13  2 12  8]
 [ 2 15  4  5  9]
 [15 14 16 14 17]
 [19  9  6 16  5]]


## numpy.diag

Syntax:

```
numpy.diag(array, k=0)
```
It extracts or constructs the diagonal elements. 

NumPy also offers built-in functions to select specific elements within ndarrays. for example., the `np.diag(ndarray, k=N)` function extracts the elements along the `diagonal` devined by `N`. As default is `k=0`, which referes tot the main diagonal. Values of `k > 0` are used to select elements in diagonals above the main diagonal, and values of `k < 0` are used to select elements in diagonals below the main diagonal. Let's see an example:

#### Example 5. Demonstrate the `diag()` function


In [12]:
# Create  a 5x5 ndarray that contains integers from 0 to 24
x = np.arange(25).reshape(5,5)

# print x 
print()
print(f"x = \n{x}")
print()

# print the elements in the main diagonal of x
print(f"z = \n {np.diag(x)}")
print()

# print the elements above the main diagonal of x 
print(f"y = \n {np.diag(x, k=1)}")
print()

#print the elements velow the main diagonal of x
print(f"w = ", np.diag(x, k=-1))


x = 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

z = 
 [ 0  6 12 18 24]

y = 
 [ 1  7 13 19]

w =  [ 5 11 17 23]


## Nunpy.unique

Syntax:
```
numpy.unique(array, return_index=False, return_inverse=False, return_counts = False, axis = None)
```

It returns the sorted unique elements of an array.

It is often useful to extract only the unique elements in a n ndarray. We can find the unique elements in an ndarray by using the `np.unique()` function. The `np.unique(ndarray)` function returns the `unique` elements in the given `ndarray`, as in the example below

#### Example 6. Demonstrate the `unique()` function



In [13]:
# create a 3x3 ndarray with repeated values
x = np.array([[1,2,3],[5,2,8],[1,2,3]])

# print x
print()
print('x = \n',x)
print()


# print the unique elements in the x are
print('The unique elements in x are: ', np.unique(x))



x = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]

The unique elements in x are:  [1 2 3 5 8]
